### ISSUE TITLE
Client or is there more implied by the protocol-suffix?

### ISSUE THREAD

**Issue by auchenberg** [watson/airplay-protocol#1]
The name of this project feels slightly confusing, as the implementation seems to be an airplay client, but the name "airplay-protocol" implies a more generic protocol abstraction that can be used by clients and servers.

**Comment by watson** [comment]
It's meant as a very low level implementation of the protocol used to connect to an AirPlay server - so I don't expect many people to use this directly. Instead devs should build more high-level modules on top of this, like [airplayer](https://github.com/watson/airplayer).

My personal goal with creating this, is so that I can build a more stable and modular version of [airplay-js](https://github.com/guerrerocarlos/node-airplay-js) which is the AirPlay client used by most projects that need to send a video to an AirPlay server today.

**Comment by auchenberg** [comment]
Cool 👍
